# R script to draw graph from csv file converted with dtgen2.pl
# (C) Copyright Satoshi Matsushita 2018
#

library(tidyverse)   # replacement reshape2
library(ggplot2)

# Local line for using Rsudio on Mac OS-X with FUSE-sshfs mount.
# setwd("/Users/matsushi/mnt/mmatom/aurora/comm_bench/Aurora")

# output file name:
outf <- "commbench-graph.png"

colors <- c("red",  "blue", "black", "red",  "blue",  "black", "red", "blue")
linetypes <- c("solid","solid","solid", "dashed","dashed","dashed", "twodash", "twodash")
ltitle <- "Src-Dest"
shapes <- c(0:10)

# read csv into data frame to wide-format data.frame
## a copule of print() line is for debugging.
rf <- read.csv(file="commbench.csv", header=T)
print(rf)

# print columnames
## cols <- colnames(rf)
## print(cols)

# Convert legend name to canonical ones.
# legend name is already this form in the logfile generated by current run.sh 
mcols <- sub("\\.", "-", cols)
print(mcols)
colnames(rf) <- mcols  # update colnames(rf)

# convert wide-format data.from to long-format with tidyr::gather()
molten <- gather(rf, key=ser, value=value, mcols[-1])
print(molten)

# To verify output on Rstudio etc.
# pdf(outf)

g <- 
  ggplot(molten, aes(x=Size/1000, y=value, group=ser)) +
  geom_point(aes(color=ser, shape=ser), size=5) +
  geom_text(aes(label=round(value, 2)),
            position=position_nudge(x=-0.1, y=0.1), check_overlap=T) +
  geom_line(aes(group=ser, linetype=ser)) +
  scale_shape_manual(values=shapes, name=ltitle, guide=guide_legend(reverse=T)) +
  scale_colour_manual(values=colors, name=ltitle, guide=guide_legend(reverse=T)) +
  scale_linetype_manual(values=linetypes, name=ltitle, guide=guide_legend(reverse=T))

# setup log axis scale and annotations
g <- g + scale_x_log10(breaks=10^(0:5))
g <- g + scale_y_log10(breaks=round(10^((-1:10)/4),2))
g <- g + annotation_logticks()
g <- g + xlab('Transfer block size (KB)') + ylab('Throughput (GB/s)')
g <- g + ggtitle('SX Aurora Tsubasa comm_bench result') +
  theme(plot.title = element_text(hjust = 0.5))

# print(g)
ggsave(file=outf, plot=g)
